name: 'checkout-files-action'
description: 'Checkout one or multiple files from a repository'
author: 'Tjitse-E'
runs:
    using: 'node16'
    main: 'dist/index.js'
inputs:
    token:
        description: Your Github
        required: true
    repo:
        description: The name of the repository (owner/repo-name)
        required: true
    paths:
        description: A multiline input of different paths that you want to clone
        required: true
    ref:
        description: "The name of the commit/branch/tag. Default: the repository’s default branch"
        required: false

